#+TITLE: Why Build Native Instead of Web Applications?
#+SUBTITLE: Since the rise of web applications, most developers and businesses have chosen to invest in web development rather than in native development. But in the battle for the future of software and civilization, and with the rise of LLMs, native development is about to make its big retvrn.
#+AUTHOR: Micah Killian
#+DATE: 2026-09-28
#+TOPIC: Industry
#+TYPE: Opinion
#+PART: 1

* The Rise of Web Applications
When I was a boy, logging into AOL and downloading game demos was the best.
While my mom and sister were playing Slingo through AOL's interface, I was busy
installing and playing the Command & Conquer demos. Browsing around, finding
games to download was nearly as enjoyable as the games themselves.

Installing the games was fantastic, too. Starting up the Command & Conquer
install wizard, watching the progress bar slowly increase over the next 20-40
minutes--different images from the game cycling while I waited...the
anticipation was incredible.

I had a similar feeling when installing other software. Remember ICQ? Remember
when installing Photoshop was exciting?

At some point, we lost that. Not only did installing applications stop being a
happy event, it started becoming a humiliation ritual. Why download and install
Discord when it's just a web application I can use in my browser? Why do I have
to pay a subscription for absolutely every single piece of useful software
(hint: Adobe started it)? Why can't I just purchase and own something?

* Technical vs. Business Priorities
The rise of web applications is partially a story about programmers making
technical decisions, and partially a story about pointy-haired bosses
vibe-managing their subordinates to build something useful as fast as possible
with no thought given to *respecting the user*. Programmers know that there were
roughly two options:

1. Make an application that is trivially cross-platform from the beginning--a web
   application. Sure, it'll take more compute, memory, and battery power, and it
   may not be a buttery-smooth experience for the user, but they'll be able to
   experience it.
2. Make an application that is cross-platform with considerable effort--a native
   GUI application. That application would respect the user's time and resources
   more, but comes at a great cost in time and effort on the part of the
   programmer.

If the programmer was the only one making the decision, he'd probably pick
option 2 most of the time, but programmers usually don't make the
decisions--that's the manager's job. The manager sees things differently:

1. Use lower-skilled, homogenized, easily replaceable web
   developers to build the thing fast.
2. Use highly-skilled, opinionated, difficult to replace native developers to
   build the thing slow.

Speed and stability of development is the key--get to market fast, and don't
blow your budget getting there. Getting the product finished and in customer's
hands quickly and cheaply is important because nobody really knows which
software is going to be successful, but we know most of it won't be, so it's
important to iterate and try lots of things out and see what the customers like.

Men that share both skill stacks and understand both the technical
and business challenges that need to be overcome are rare, and they usually have
a boss that isn't technical. They must make a cost-benefit analysis taking into
account both the technical and business sides of software development, and
usually they will weigh the business side more heavily out of both a desire to
make cool things that people like and to climb the career ladder.

* Native Development is Risky--or it was.
I don't want to cheapen the costs of native development either. Building
software is risky because we don't know the future. We don't know what people
really like or want much of the time, especially if we are making something
completely new. Native development explodes the size of that risk enormously. If
risk is expensive, it's scary. And if it's scary, it probably won't happen.

I actually find the SpaceX Raptor engine development as the model for good
software development: initially overly complex, ugly, and inefficient--with the
intention of iterating upon and improving the final product into something
beautiful--something you can be proud of both for its utility and aesthetic
appeal both to normies and your peers.

That's why I always supported businesses and individuals starting with an
Electron application. Making a web-native application is ugly and nothing you
can be proud of as a programmer. But it allows you to try things out cheaply and
quickly, get feedback from users, and iterate on the product after that.
Software development that follows the Raptor model is the ideal and should be
encouraged.

But the problem is that the decision makers never have the intention of
following that model of development. They are happy to vibe-manage their way to
seniority and a golden parachute when the consequences of their vibing catch up
to them. Usually they aren't in a good position to do otherwise--a series of
catastrophic decisions by vibe-politicians (WWI & WWII were optional; Keynesian
monetary policy has been pure cultural poison; Communists were not
systematically identified and executed; post WWII wealth in America produced a
population of weak, soft, and selfish old men who did not care to maintain the
prosperous civilization they inherited), vibe-investors (clueless, degenerate,
Mammon-worshipping VCs pumping companies with strings-attached money), and
vibe-educators (those demonic Communists making young people political
revolutionaries devoid of even basic, marketable skills) have so distorted and
corrupted the civilization that built the Golden Gate Bridge and Hoover Dam (in
MONTHS), sent men to the Moon on kilobytes of memory, and produced energy from
glowing hot metal that the vibe-managers can hardly be blamed for not giving a
damn about the memory efficiency of their vibe-managed chat client or the poor
performance of their vibe-managed video game.

The calculus changes with LLMs, however. People /who give a damn/ are slowly
being granted superhuman powers to actually fight back against the people /who
don't/. The risk of native development--a proxy term for any development
conducted by people who care about making the future better for everybody via
thoughtful software development--is greatly decreased with LLMs. The Good Guys
have the ability to circumvent the destructive influence of the wicked Vibers
and make *great* software. You can make a native application quickly and cheaply
with a much smaller group of people (maybe even just you, the handsome reader!).
You don't have to answer to anyone or anything else except your users (I pray
you get many), your inner voice, and to God.

* The RETVRN of Native Applications
That's why I'm giving native application development a try. I also believe this
will be the trend for the next decade and generation of programmers. That
explains a strange phenomenon skeptical software engineers have noticed:
Tremendous enthusiasm and hype behind LLMs, but no tangible increase in the
quality of our /current/ software. For the most part, software developers have
witness only a visceral *decrease* in quality of software because of LLMs.
Businesses clumsily adding "AI" to their product and distracting the user; New
software on app markets that is obviously vibe coded with no respect to the
user--just a quick payday; Vibe-copied software that is visibly inferior to the
original.

Furthermore, normies have noticed that they can't pick up their phone or read
their email without some Nigerian or Indian scammer trying to steal their
life-savings or Bitcoins from them. We, the Situation Monitors, know that these
scams are supercharged by LLMs. Scammers use LLMs to correct their English to
make their communications appear genuine. They use LLMs to produce voices of
family members during phone calls or produce realistic human images during
completely LLM conducted video calls. Avoiding these scams is /hard/ for our
elder parents and those calls contribute to an ever decreasing trust in society.

So for various reasons, both the Initiated and the Commoner have mostly been
exposed to the negative influences of LLMs.

But LLMs are a /force multiplier/, either for Good or Evil. And We Who Give A
Damn are busily working outside the current corporate/investment structure to
find our place as part of the forces for Good. That would explain why the
initial, visible products of LLM use appear negative, yet there are still so
many people optimistic for a future using LLMs. The Sons of Mammon have taken
first blood in the battle for the future of software and civilization, but the
war has just begun.

